name: azan_kz
description: Azan.kz site

version: 1.0.5+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter:
  flutter_statusbarcolor:

flutter:
  uses-material-design: true
