name: azan_kz
description: Azan.kz app

publish_to: 'none'

version: 2.0.0+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  webview_flutter: ^2.0.12

flutter:
  uses-material-design: true
